apiVersion: v1
kind: Service
metadata:
  name: kyc-service
  labels:
    app: kyc
spec:
  type: NodePort
  selector:
    app: kyc
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000  # Must be between 30000–32767
